In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.naive_bayes import GaussianNB

print("Setup is working")

Setup is working

In [1]:
import os

print("Current working folder:", os.getcwd())

Current working folder: c:\Users\tonik\OneDrive\Desktop\551\Gaussian_Final_Task\notebook

In [2]:
dataset_path = "../data/dataset.csv"
print("Dataset path is ready:", dataset_path)

Dataset path is ready: ../data/dataset.csv

In [3]:
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix

print("Model tools are ready")

Model tools are ready

# Gaussian Classification Model
## Setup Ready for Dataset

In [4]:
from pathlib import Path

base_path = Path(r"C:\Users\tonik\OneDrive\Desktop\551\Gaussian_Final_Task\data\Data_clean\Data_clean")

csv_files = list(base_path.rglob("*.csv"))

print("Total CSV files found:", len(csv_files))
print("First 10 files:")
for f in csv_files[:10]:
    print(f)

Total CSV files found: 1821
First 10 files:
C:\Users\tonik\OneDrive\Desktop\551\Gaussian_Final_Task\data\Data_clean\Data_clean\G04\person10\Backward\BrainFlow-RAW_2025-03-24_21-14-10_100.csv
C:\Users\tonik\OneDrive\Desktop\551\Gaussian_Final_Task\data\Data_clean\Data_clean\G04\person10\Backward\BrainFlow-RAW_2025-03-24_21-14-10_101.csv
C:\Users\tonik\OneDrive\Desktop\551\Gaussian_Final_Task\data\Data_clean\Data_clean\G04\person10\Backward\BrainFlow-RAW_2025-03-24_21-14-10_102.csv
C:\Users\tonik\OneDrive\Desktop\551\Gaussian_Final_Task\data\Data_clean\Data_clean\G04\person10\Backward\BrainFlow-RAW_2025-03-24_21-14-10_103.csv
C:\Users\tonik\OneDrive\Desktop\551\Gaussian_Final_Task\data\Data_clean\Data_clean\G04\person10\Backward\BrainFlow-RAW_2025-03-24_21-14-10_104.csv
C:\Users\tonik\OneDrive\Desktop\551\Gaussian_Final_Task\data\Data_clean\Data_clean\G04\person10\Backward\BrainFlow-RAW_2025-03-24_21-14-10_95.csv
C:\Users\tonik\OneDrive\Desktop\551\Gaussian_Final_Task\data\Data_clean\Data_clean\G04\person10\Backward\BrainFlow-RAW_2025-03-24_21-14-10_96.csv
C:\Users\tonik\OneDrive\Desktop\551\Gaussian_Final_Task\data\Data_clean\Data_clean\G04\person10\Backward\BrainFlow-RAW_2025-03-24_21-14-10_97.csv
C:\Users\tonik\OneDrive\Desktop\551\Gaussian_Final_Task\data\Data_clean\Data_clean\G04\person10\Backward\BrainFlow-RAW_2025-03-24_21-14-10_98.csv
C:\Users\tonik\OneDrive\Desktop\551\Gaussian_Final_Task\data\Data_clean\Data_clean\G04\person10\Backward\BrainFlow-RAW_2025-03-24_21-14-10_99.csv

In [5]:
import pandas as pd

sample_file = csv_files[0]
print("Sample file:", sample_file)

df_sample = pd.read_csv(sample_file)

print("Shape:", df_sample.shape)
print("Columns:")
print(df_sample.columns.tolist())

df_sample.head()

Sample file: C:\Users\tonik\OneDrive\Desktop\551\Gaussian_Final_Task\data\Data_clean\Data_clean\G04\person10\Backward\BrainFlow-RAW_2025-03-24_21-14-10_100.csv
Shape: (47897, 1)
Columns:
['90.000000\t-3359.243674\t572.025844\t-187500.022352\t187500.000000\t-37880.909488\t-39671.261867\t33002.775371\t-2496.131062\t-27377.668307\t-20223.523107\t-11390.337216\t-13440.126293\t10758.162827\t-22295.328652\t-187500.022352\t-187500.022352\t0.000000\t0.000000\t0.000000\t192.000000\t0.000000\t0.000000\t0.000000\t0.000000\t0.000000\t0.000000\t0.000000\t0.000000\t0.000000\t1742870098.446785\t0.000000']

  90.000000\t-3359.243674\t572.025844\t-187500.022352\t187500.000000\t-37880.909488\t-39671.261867\t33002.775371\t-2496.131062\t-27377.668307\t-20223.523107\t-11390.337216\t-13440.126293\t10758.162827\t-22295.328652\t-187500.022352\t-187500.022352\t0.000000\t0.000000\t0.000000\t192.000000\t0.000000\t0.000000\t0.000000\t0.000000\t0.000000\t0.000000\t0.000000\t0.000000\t0.000000\t1742870098.446785\t0.000000
0  92.000000\t-3373.928770\t550.992853\t-187500.0...
1  94.000000\t-3342.077534\t576.317379\t-187500.0...
2  96.000000\t-3366.239770\t561.654635\t-187500.0...
3  98.000000\t-3363.646968\t569.410690\t-187500.0...
4  100.000000\t-3380.611942\t574.350426\t-187500....

In [6]:
df_sample = pd.read_csv(sample_file, sep="\t", header=None)

print("Shape:", df_sample.shape)
df_sample.head()

Shape: (47898, 32)

,0,1,2,3,4,5,6,7,8,9,...,22,23,24,25,26,27,28,29,30,31
0,90.0,-3359.243674,572.025844,-187500.022352,187500.0,-37880.909488,-39671.261867,33002.775371,-2496.131062,-27377.668307,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.742870e+09,0.0
1,92.0,-3373.928770,550.992853,-187500.022352,187500.0,-37887.369142,-39680.426083,33016.365232,-2460.815306,-27394.096839,...,96.0,15.0,112.0,124.0,48.0,0.0,0.0,0.0,1.742870e+09,0.0
2,94.0,-3342.077534,576.317379,-187500.022352,187500.0,-37868.705436,-39661.181231,33016.745212,-2502.546013,-27385.647879,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.742870e+09,0.0
3,96.0,-3366.239770,561.654635,-187500.022352,187500.0,-37879.143700,-39669.764301,33011.045517,-2464.279826,-27377.042458,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.742870e+09,0.0
4,98.0,-3363.646968,569.410690,-187500.022352,187500.0,-37874.829814,-39669.965466,33024.680081,-2491.638361,-27395.057964,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.742870e+09,0.0

In [ ]:
def extract_features(file_path):
    df = pd.read_csv(
        file_path,
        sep="\t",
        header=None,
        dtype=str,
        low_memory=False
    )

    features = {}

    for col in df.columns:
        col_data = pd.to_numeric(df[col], errors="coerce").fillna(0)
        features[f"col_{col}_mean"] = col_data.mean()
        features[f"col_{col}_std"] = col_data.std()
        features[f"col_{col}_min"] = col_data.min()
        features[f"col_{col}_max"] = col_data.max()

    features["label"] = file_path.parent.name
    features["person"] = file_path.parent.parent.name
    features["group"] = file_path.parent.parent.parent.name

    return features

In [ ]:
all_features = [extract_features(file) for file in csv_files]

features_df = pd.DataFrame(all_features)

print("Dataset shape:", features_df.shape)
print("\nLabel counts:")
print(features_df["label"].value_counts())

features_df.head()

NameError: name 'csv_files' is not defined

In [ ]:
from pathlib import Path
import pandas as pd

base_path = Path(r"C:\Users\tonika\OneDrive\Desktop\551\Gaussian_Final_Task\data\Data_clean\Data_clean")
csv_files = list(base_path.rglob("*.csv"))

print("Total CSV files found:", len(csv_files))

Total CSV files found: 1821

In [ ]:
from pathlib import Path
from collections import defaultdict
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import accuracy_score, classification_report

# 1. Find all CSV files
base_path = Path(r"C:\Users\tonik\OneDrive\Desktop\551\Gaussian_Final_Task\data\Data_clean\Data_clean")
csv_files = list(base_path.rglob("*.csv"))
print("Total CSV files found:", len(csv_files))

# 2. Make a smaller balanced subset so it finishes faster
files_by_label = defaultdict(list)
for f in csv_files:
    files_by_label[f.parent.name].append(f)

quick_files = []
for label in sorted(files_by_label.keys()):
    quick_files.extend(files_by_label[label][:20])   # 20 files per class

print("Using quick subset:", len(quick_files))
print("Labels:", sorted(files_by_label.keys()))

# 3. Fast feature extraction
def extract_features_fast(file_path):
    df = pd.read_csv(file_path, sep="\t", header=None, dtype=str, low_memory=False)
    df = df.apply(pd.to_numeric, errors="coerce").fillna(0)

    # downsample rows for speed
    df = df.iloc[::25, :]

    features = {}
    for col in df.columns:
        s = df[col]
        features[f"col_{col}_mean"] = s.mean()
        features[f"col_{col}_std"] = s.std()

    features["label"] = file_path.parent.name
    return features

# 4. Build ML table
rows = []
for i, f in enumerate(quick_files, 1):
    rows.append(extract_features_fast(f))
    if i % 10 == 0 or i == len(quick_files):
        print(f"Processed {i}/{len(quick_files)} files")

features_df = pd.DataFrame(rows)
print("Feature table shape:", features_df.shape)

# 5. Train/test split
X = features_df.drop(columns=["label"])
y = features_df["label"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# 6. Baseline model
baseline_model = GaussianNB()
baseline_model.fit(X_train, y_train)
y_pred_base = baseline_model.predict(X_test)
baseline_acc = accuracy_score(y_test, y_pred_base)

print("\nBaseline Accuracy:", baseline_acc)
print("\nBaseline Report:\n")
print(classification_report(y_test, y_pred_base))

# 7. Improved model
param_grid = {"var_smoothing": np.logspace(0, -9, 10)}
grid = GridSearchCV(GaussianNB(), param_grid, cv=3, scoring="accuracy")
grid.fit(X_train, y_train)

best_model = grid.best_estimator_
y_pred_best = best_model.predict(X_test)
improved_acc = accuracy_score(y_test, y_pred_best)

print("Best var_smoothing:", grid.best_params_)
print("Improved Accuracy:", improved_acc)

print("\nImproved Report:\n")
print(classification_report(y_test, y_pred_best))